# Generated by Django 4.2.25 on 2025-11-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_language',
        ),
    ]
