# Generated by Django 4.2.25 on 2025-10-31 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('content', models.TextField(blank=True, verbose_name='Вміст')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='URL')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='URL зображення')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Джерело')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категорія')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Мова')),
                ('country', models.CharField(blank=True, max_length=10, verbose_name='Країна')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Збережено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle', verbose_name='Новина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Збережена новина',
                'verbose_name_plural': 'Збережені новини',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_articles', through='news.SavedArticle', to=settings.AUTH_USER_MODEL, verbose_name='Збережено користувачами'),
        ),
    ]
