# Generated by Django 4.2.25 on 2025-11-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL зображення'),
        ),
    ]
