# Generated by Django 4.2.25 on 2025-11-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='country',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='language',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='published_at',
        ),
    ]
